export const BLOG_CATEGORIES = [
  'All',
  'AI & Voice',
  'Industry Insights',
  'Product Updates',
  'Case Studies',
  'Compliance',
  'Engineering',
];

export const BLOG_POSTS = [
  {
    id: 'featured-singapore-frontdesk',
    slug: 'singapore-frontdesk-ai-voice',
    featured: true,
    category: 'Industry Insights',
    title: 'Field notes from Singapore\'s front desk.',
    subtitle: 'How AI voice agents are quietly replacing hold music across Singapore\'s busiest clinics, banks, and property firms — one call at a time.',
    excerpt: 'Walk into any Singapore clinic on a Monday morning and the phones never stop. We spent three weeks embedded with front-desk teams across four verticals to understand what breaks, what scales, and what customers actually want to hear.',
    readTime: '8 min read',
    date: 'Jul 18, 2026',
    author: { name: 'Riya Mehta', role: 'Head of Research', initials: 'RM', color: '#F97316' },
    tags: ['Singapore', 'Healthcare', 'Real Estate', 'Field Research'],
    image: null,
    accentColor: '#F97316',
  },
  {
    id: 'sub-300ms-latency',
    slug: 'sub-300ms-voice-latency-how-we-did-it',
    featured: false,
    category: 'Engineering',
    title: 'How we hit sub-300ms voice latency in production',
    excerpt: 'Building a real-time AI phone agent that doesn\'t feel robotic means winning the latency war. Here\'s the exact stack, trade-offs, and lessons from our infra team.',
    readTime: '11 min read',
    date: 'Jul 10, 2026',
    author: { name: 'Arjun Sharma', role: 'Lead Engineer', initials: 'AS', color: '#F97316' },
    tags: ['Engineering', 'Performance', 'Infrastructure'],
    accentColor: '#F97316',
  },
  {
    id: 'hipaa-voice-agents',
    slug: 'hipaa-compliant-voice-agents-guide',
    featured: false,
    category: 'Compliance',
    title: 'The definitive guide to HIPAA-compliant AI voice agents',
    excerpt: 'HIPAA compliance for voice AI is not just about encryption. Audit trails, BAA agreements, minimum necessary access, and call recording retention all come into play.',
    readTime: '9 min read',
    date: 'Jul 4, 2026',
    author: { name: 'Priya Nair', role: 'Compliance Lead', initials: 'PN', color: '#F97316' },
    tags: ['HIPAA', 'Compliance', 'Healthcare'],
    accentColor: '#F97316',
  },
  {
    id: 'real-estate-lead-qual',
    slug: 'real-estate-ai-lead-qualification',
    featured: false,
    category: 'Case Studies',
    title: '3× faster lead qualification for a Mumbai property firm',
    excerpt: 'A 140-agent real-estate brokerage replaced their inbound call queue with Conciva AI. Six weeks later, site-visit bookings were up 65% and cost-per-lead dropped by 40%.',
    readTime: '6 min read',
    date: 'Jun 27, 2026',
    author: { name: 'Kiran Patel', role: 'Solutions Engineer', initials: 'KP', color: '#F97316' },
    tags: ['Real Estate', 'Case Study', 'ROI'],
    accentColor: '#F97316',
  },
  {
    id: 'multilingual-voice-models',
    slug: 'training-multilingual-voice-models',
    featured: false,
    category: 'AI & Voice',
    title: 'Training voice models that sound native in 10 Indian languages',
    excerpt: 'Hinglish isn\'t a dialect — it\'s a code-switch. Building voice AI that handles mid-sentence language blending required us to rethink tokenisation, prosody, and training data sourcing from scratch.',
    readTime: '13 min read',
    date: 'Jun 20, 2026',
    author: { name: 'Arjun Sharma', role: 'Lead Engineer', initials: 'AS', color: '#F97316' },
    tags: ['NLP', 'Voice AI', 'Multilingual'],
    accentColor: '#F97316',
  },
  {
    id: 'conciva-v2-launch',
    slug: 'conciva-ai-v2-platform-launch',
    featured: false,
    category: 'Product Updates',
    title: 'Conciva AI v2: custom voice personas, live dashboards, and new CRM sync',
    excerpt: 'Today we\'re shipping the biggest platform update since launch — brand-new voice persona builder, real-time call analytics, bi-directional HubSpot & Salesforce sync, and a redesigned agent studio.',
    readTime: '5 min read',
    date: 'Jun 12, 2026',
    author: { name: 'Riya Mehta', role: 'Head of Research', initials: 'RM', color: '#F97316' },
    tags: ['Product', 'Launch', 'CRM'],
    accentColor: '#F97316',
  },
  {
    id: 'edtech-admissions',
    slug: 'edtech-ai-admissions-helpline',
    featured: false,
    category: 'Case Studies',
    title: 'How an EdTech firm handled 100× admission calls without adding headcount',
    excerpt: 'Peak admission season means 10,000 calls in 72 hours. We walk through how a coaching institute deployed Conciva AI in five days and scaled without a single new hire.',
    readTime: '7 min read',
    date: 'Jun 5, 2026',
    author: { name: 'Priya Nair', role: 'Compliance Lead', initials: 'PN', color: '#F97316' },
    tags: ['EdTech', 'Case Study', 'Scale'],
    accentColor: '#F97316',
  },
  {
    id: 'voice-ai-vs-chatbot',
    slug: 'voice-ai-vs-chatbot-which-wins',
    featured: false,
    category: 'AI & Voice',
    title: 'Voice AI vs chatbots: which actually converts better?',
    excerpt: 'We ran a six-month A/B study across 2.4 million customer interactions. The results surprised even us — voice wins on conversion, chat wins on containment. Here\'s the full breakdown.',
    readTime: '10 min read',
    date: 'May 28, 2026',
    author: { name: 'Kiran Patel', role: 'Solutions Engineer', initials: 'KP', color: '#F97316' },
    tags: ['Voice AI', 'Chatbot', 'Research'],
    accentColor: '#F97316',
  },
];
